version: '3'

services:
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      # RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      # RABBITMQ_DEFAULT_USER: "dev"
      # RABBITMQ_DEFAULT_PASS: "dev"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

  notification-service:
    image: test_notification_service
    ports:
      - "5000:5000"
    environment:
      - RABBIT_HOST=rabbit1
    depends_on:
      - rabbit1
    # links:
    #   - rabbit1:broker

  # nginx
  proxy1:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
        # Проброс конфигурации внутрь контейнера
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        # Проброс конфигурации внутрь контейнера
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
        # Проброс логов из контейнера
      # - /docker-data/notification-service/logs/proxy/:/var/log/nginx
    depends_on:
      - notification-service
    restart: always